name: Build

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.2 
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: wokwi-cli-github-actions-example

      - name: Initialize
        working-directory: wokwi-cli-github-actions-example
        run: |
          west init -l .
          west update
          west zephyr-export
      - name: Build firmware
        working-directory: wokwi-cli-github-actions-example/app
        run: |
          west build -b esp32c3_devkitm .
      - name: Install the Wokwi CLI
        run: |
          wget -O /usr/local/bin/wokwi-cli https://github.com/wokwi/wokwi-cli/releases/latest/download/wokwi-cli-linuxstatic-x64
          chmod +x /usr/local/bin/wokwi-cli

      - name: Test with Wokwi
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          timeout: 1000
          expect_text: 'Hello World!'
          path: wokwi-cli-github-actions-example